struct {
	char *scramble;
	char *solutions;
} s[] = {
[0] = {
	.scramble = "B L' U' F2 D R F R F2 B' U D2 R2 F2 L2 B2 R2 F2 U F2",
	.solutions =
		"F D L B' U\n"
		"F D B' L2 U\n"
		"F B' D L2 U\n"
		"F' D L B' U\n"
		"F' D B' L2 U\n"
		"F' B' D L2 U\n"
		"U F U B D\n"
		"U F U' B D\n"
		"U F' U B D\n"
		"U F' U' B D\n"
		"F B' U B2 D\n"
		"F' B' U B2 D\n"
		"B U F D U\n"
		"B U F' D U\n"
		"(D' F D L U)\n"
		"(D' F D' L U)\n"
		"(D' F' D L U)\n"
		"(D' F' D' L U)\n"
		"(F L' D L2 U)\n"
		"(F' L' D L2 U)\n"
		"(F U L' B2 D)\n"
		"(F U B L' D)\n"
		"(F L' U B2 D)\n"
		"(F' U L' B2 D)\n"
		"(F' U B L' D)\n"
		"(F' L' U B2 D)\n"
		"(D' L' F D U)\n"
		"(D' L' F' D U)\n"
		"U (L U B D)\n"
		"U (L U' B D)\n"
		"D L' F U (U)\n"
		"D F L2 U (U)\n"
		"L' F U (L U)\n"
		"F L2 U (L U)\n"
		"U B' D (D U)\n"
		"U' B' D (D U)\n"
		"D2 F' D (F' U)\n"
		"L B D (F' U)\n"
		"B U F D (D)\n"
		"B U' F D (D)\n"
		"B' U F D (D)\n"
		"B' U' F D (D)\n"
		"D U (U B' D)\n"
		"D U (U' B' D)\n"
},
[1] = {
	.scramble = "L' U' D' F' R2 L F2 D L F2 L2 F2 L2 U L2 D F2 U2 B2 U'",
	.solutions =
		"U (R2 L' U)\n"
		"D R' U (D)\n"
		"D' R' U (D)\n"
},
[2] = {
	.scramble = "F2 L F' B2 D F R' U2 B R2 U' R2 D' L2 D2 B2 U' L2 U2",
	.solutions =
		"B U (F' D)\n"
		"B2 U (F D)\n"
},
[3] = {
	.scramble = "R2 U' F2 R L' U D' B R' F R2 B U2 R2 B U2 B' L2 F' D2 F' L2",
	.solutions =
		"(R L D U)\n"
		"(R L' D U)\n"
		"(R' L D U)\n"
		"(R' L' D U)\n"
},
[4] = {
	.scramble = "B' U' R U' B L' B' U F' L U F2 R2 F2 D F2 B2 D2 L2 U' B2 U'",
	.solutions =
		"D L U (B' U)\n"
		"D' L U (B' U)\n"
		"L U B D (U)\n"
		"L U' B D (U)\n"
		"D U (R B' U)\n"
		"D U (B' R U)\n"
},
[5] = {
	.scramble = "D R' F' D' B' R B' U' F R' B2 R F2 R' D2 B2 L B2 L2 U2 D2 L'",
	.solutions =
		"F D L2 B U\n"
		"F D B L2 U\n"
		"F B D L2 U\n"
		"F' D L2 B U\n"
		"F' D B L2 U\n"
		"F' B D L2 U\n"
		"U F U B' D\n"
		"U F U' B' D\n"
		"U F' U B' D\n"
		"U F' U' B' D\n"
		"F B U B2 D\n"
		"F' B U B2 D\n"
		"B' U F D U\n"
		"B' U F' D U\n"
		"(F U R2 L D)\n"
		"(F' U' R' L2 D)\n"
		"L B' D (B2 U)\n"
		"B' D (U2 F U)\n"
		"B' D (L' B' U)\n"
		"B' L D (B2 U)\n"
},
[6] = {
	.scramble = "B U' F L D' R2 F2 R' F2 U' D2 B L2 F' R2 B' U2 B U2 R2",
	.solutions =
		"U L F B' D\n"
		"U B' L F D\n"
		"U' L F B' D\n"
		"U' B' L F D\n"
		"F' U L B' D\n"
		"F' U B' L D\n"
		"F' U' L B' D\n"
		"F' U' B' L D\n"
		"(B L D R U)\n"
		"(B L D' R U)\n"
		"(B L' D R U)\n"
		"(B L' D' R U)\n"
		"(R' L U B' D)\n"
		"(R' L U' B' D)\n"
		"(R' L' U B' D)\n"
		"(R' L' U' B' D)\n"
		"(R' B L D U)\n"
		"(R' B L' D U)\n"
		"U (R F2 L' U)\n"
		"U (F2 R2 L' U)\n"
		"U (D R' B2 D)\n"
		"U (D B2 R' D)\n"
		"U (R' B2 L' D)\n"
		"U (F L B2 D)\n"
		"U (F B2 L D)\n"
		"U (B2 D2 R' D)\n"
		"R2 U (L B2 D)\n"
		"R2 U (B2 L D)\n"
		"U F' L' D (D)\n"
		"U B' D (F2 U)\n"
		"U' F' L' D (D)\n"
		"U' B' D (F2 U)\n"
		"L U F' D (D)\n"
		"L U' F' D (D)\n"
},
[7] = {
	.scramble = "U2 D' F' U' R' U B' R D2 F U2 D F2 U2 B2 D' B2 L2 U2 D'",
	.solutions =
		"L' D F' B' U\n"
		"L' D' F' B' U\n"
		"F L' D B' U\n"
		"F L' D' B' U\n"
		"(U' R D B' U)\n"
		"(U' R D' B' U)\n"
		"(U' R' D B' U)\n"
		"(U' R' D' B' U)\n"
		"(R D L B U)\n"
		"(R D' L B U)\n"
		"(R B' D L U)\n"
		"(R B' D' L U)\n"
		"(U' B R D U)\n"
		"(U' B R' D U)\n"
		"(B U2 R D U)\n"
		"(B U2 R' D U)\n"
		"D B' U (F' D)\n"
		"D' F2 B' U (D)\n"
		"D' B' U (F' D)\n"
		"F2 B2 U (R D)\n"
		"F2 B' U (R2 D)\n"
		"R2 L2 D (R D)\n"
		"R2 L' D (R' D)\n"
},
[8] = {
	.scramble = "L D R D2 B D R U B' D B2 D' L2 U2 R2 D L2 U L2 U2 F2",
	.solutions =
		"(F B' L' U)\n"
		"(B' L' F2 U)\n"
		"(R2 B L D)\n"
		"(B R2 L D)\n"
		"R U (L' U)\n"
},
[9] = {
	.scramble = "R' D2 L B2 U B D F2 L U L2 U2 L2 U R2 U' F2 D2 F2 U2 B2",
	.solutions =
		"D (U' R2 U)\n"
		"D (D' F2 D)\n"
},
[10] = {
	.scramble = "F' B2 U2 D R' U F R D R' U2 B2 R U2 R U2 R' D2 R' B2 L'",
	.solutions =
		"U' R2 F' B U\n"
		"U' F' R' B U\n"
		"U' F' B R2 U\n"
		"U' B R F' U\n"
		"U' L2 F B' D\n"
		"U' F L2 B' D\n"
		"U' F B' L2 D\n"
		"U' B' L2 F D\n"
		"B D' U F D\n"
		"B D' U' F D\n"
		"B' U' L2 F D\n"
		"B' U' F L2 D\n"
		"(L2 F D B2 U)\n"
		"(L2 F' D B2 U)\n"
		"(F D' F2 B' U)\n"
		"(L2 F U R2 D)\n"
		"(L2 F' U R2 D)\n"
		"U (U R B' U)\n"
		"U (U B' R U)\n"
		"U (U' L F' U)\n"
		"U (U' F' L U)\n"
		"U (R U2 B' U)\n"
		"U (R L F U)\n"
		"U (F' U2 L U)\n"
		"U (F' B' R' U)\n"
		"F' U (U2 B' U)\n"
		"F' U (L F U)\n"
		"D (U2 F D U)\n"
		"D (U2 F' D U)\n"
		"F2 B' D (F D)\n"
		"B2 D (U F D)\n"
		"B2 D (U' F D)\n"
},
[11] = {
	.scramble = "D2 R' U F' D' R2 D' L2 F R D2 R' F2 R2 U2 R U2 B2 R2 U2 B2",
	.solutions =
		"L F' U\n"
		"F' L U\n"
},
[12] = {
	.scramble = "F' U' D B2 U2 F R2 D' R U R2 L2 F2 D F2 U L2 D' R2 F2",
	.solutions =
		"B' D R2 B U\n"
		"B U' F B2 D\n"
		"D R' L2 U (D)\n"
		"R' U (R' B2 D)\n"
		"R' U (B2 R' D)\n"
		"R' L2 U (R' D)\n"
		"U2 B2 D (F' D)\n"
		"D2 F2 D (F' D)\n"
		"F2 D (F2 R' D)\n"
		"B' D (D2 B D)\n"
		"B' D (L' F' D)\n"
},
[13] = {
	.scramble = "R2 U2 B' D2 R' D2 L' B2 U2 D' B' L2 B2 L2 B' L2 F' U2 L2 F U2 B",
	.solutions =
		"(R2 L' D)\n"
},
[14] = {
	.scramble = "R2 L' F' R B' U F D2 R' B R2 B L2 D2 L2 B' U2 F D2 B2 D2",
	.solutions =
		"R2 F B' U\n"
		"F R2 B' U\n"
		"F B' R2 U\n"
		"B' R2 F U\n"
		"L2 F' B D\n"
		"F' L' B D\n"
		"F' B L2 D\n"
		"B L F' D\n"
		"(F2 B R U)\n"
		"(R L2 B D)\n"
},
[15] = {
	.scramble = "U' L' U L2 D2 F D L' U B2 L2 B' R2 U2 B U2 R2 L2 B' D2",
	.solutions =
		"D (R2 D)\n"
},
[16] = {
	.scramble = "F U2 F R2 U' D' B R' U2 R' U2 L2 U2 B2 R' D2 B2 R B2 L' F2",
	.solutions =
		"(D U2 F U)\n"
		"(D L' B' U)\n"
		"(D' U2 F U)\n"
		"(D' L' B' U)\n"
		"(L2 D B' U)\n"
		"(L2 D' B' U)\n"
},
[17] = {
	.scramble = "U F2 R' L F' U2 F D' L' U D2 B' R2 F' D2 B' L2 B'",
	.solutions =
		"U2 R' B D' L2 U\n"
		"U2 R' B' D' L2 U\n"
		"U2 B D' R L2 U\n"
		"U2 B' D' R L2 U\n"
		"R L' F D L2 U\n"
		"R L' F' D L2 U\n"
		"R F D L2 F U\n"
		"R' U2 B D R2 U\n"
		"R' U2 B' D R2 U\n"
		"R' U' B D' L2 U\n"
		"R' U' B' D' L2 U\n"
		"R' B D' L2 F U\n"
		"L2 D' F D R' U\n"
		"L2 D' F D' R' U\n"
		"L2 D' F' D R' U\n"
		"L2 D' F' D' R' U\n"
		"L' F D R' L2 U\n"
		"L' F' D R' L2 U\n"
		"F U B' D R' U\n"
		"F U B' D' R' U\n"
		"F U' B D L U\n"
		"F U' B D' L U\n"
		"F D R' L2 F U\n"
		"F D L2 F R' U\n"
		"F D' R2 L F' U\n"
		"F D' R2 F' L U\n"
		"F B D U' L U\n"
		"F B D' U' L U\n"
		"F B' D U R' U\n"
		"F B' D' U R' U\n"
		"F' B D R2 L U\n"
		"F' B' D' R' L2 U\n"
		"B D R L F' U\n"
		"B D R F' L U\n"
		"B D L F' R2 U\n"
		"B D F' R2 L U\n"
		"B D' R L2 F U\n"
		"B' D' L2 F' R' U\n"
		"B' D' F' R' L2 U\n"
		"B' R D' L2 F' U\n"
		"B' R D' F' L2 U\n"
		"B' R F' D' L2 U\n"
		"U R U F B D\n"
		"U R U' F B D\n"
		"U B' R U F D\n"
		"U B' R U' F D\n"
		"U2 R' B U' F2 D\n"
		"U2 R' B' U' F2 D\n"
		"R L' F U B2 D\n"
		"R L' F' U B2 D\n"
		"R F' U' F2 B D\n"
		"R' U2 B U F2 D\n"
		"R' U2 B' U F2 D\n"
		"R' U' B U' F2 D\n"
		"R' U' B' U' F2 D\n"
		"L2 F U' B2 L' D\n"
		"L2 F' U' B2 L' D\n"
		"B D L' F B2 D\n"
		"B D F L' B2 D\n"
		"B D F B L' D\n"
		"B D B L' F D\n"
		"B D' F B2 R D\n"
		"B2 D L' F B' D\n"
		"B2 D F L' B' D\n"
		"B2 D' F R B D\n"
		"B' U R U F D\n"
		"B' U R U' F D\n"
		"B' D F B2 L' D\n"
		"B' D B2 L' F D\n"
		"B' D' F R B2 D\n"
		"B' D' F B' R D\n"
		"B' R F' U' F2 D\n"
		"R L2 D' F D U\n"
		"R L2 D' F' D U\n"
		"L2 D' R F D U\n"
		"L2 D' R F' D U\n"
		"(U2 L D F' B2 U)\n"
		"(U2 L' D F' B2 U)\n"
		"(U2 F L D B2 U)\n"
		"(U2 F L' D B2 U)\n"
		"(R L D F B2 U)\n"
		"(R L' D' F2 B' U)\n"
		"(R' U L' D B' U)\n"
		"(R' U L' D' B' U)\n"
		"(R' U' L D F U)\n"
		"(R' U' L D' F U)\n"
		"(R' D F2 R B' U)\n"
		"(R' D F2 B' R U)\n"
		"(R' D' F B2 R' U)\n"
		"(R' D' B2 R' F U)\n"
		"(R' L D U' F U)\n"
		"(R' L D' U' F U)\n"
		"(R' L' D U B' U)\n"
		"(R' L' D' U B' U)\n"
		"(L D R F B2 U)\n"
		"(L D B2 R F U)\n"
		"(L F' D R B2 U)\n"
		"(L F' D B2 R U)\n"
		"(L F' R D B2 U)\n"
		"(L' D F' B2 R' U)\n"
		"(L' D' R F2 B' U)\n"
		"(L' D' F' R B' U)\n"
		"(L' D' F' B' R U)\n"
		"(L' D' B' R F2 U)\n"
		"(F U L D B2 U)\n"
		"(F U L' D B2 U)\n"
		"(F U2 L D' F2 U)\n"
		"(F U2 L' D' F2 U)\n"
		"(F L' D B2 R' U)\n"
		"(F' R' D' B2 R' U)\n"
		"(F' B R D' B2 U)\n"
		"(F' B R' D' B2 U)\n"
		"(B R D' F B2 U)\n"
		"(B R' D' F B2 U)\n"
		"(B2 D R D F U)\n"
		"(B2 D R D' F U)\n"
		"(B2 D R' D F U)\n"
		"(B2 D R' D' F U)\n"
		"(U2 F L U R2 D)\n"
		"(U2 F L' U R2 D)\n"
		"(U' L F' U R' D)\n"
		"(U' L F' U' R' D)\n"
		"(U' F' U R' L' D)\n"
		"(U' F' U' R' L' D)\n"
		"(L U' F' U R' D)\n"
		"(L U' F' U' R' D)\n"
		"(L D R' L F' D)\n"
		"(L D R' F' L2 D)\n"
		"(L D' R' L2 B D)\n"
		"(L D' L2 B R' D)\n"
		"(L F' R U R2 D)\n"
		"(L2 D R' F' L' D)\n"
		"(L2 D' R' B L D)\n"
		"(L2 D' B R' L D)\n"
		"(L' D R' L2 F' D)\n"
		"(L' D' R' L' B D)\n"
		"(L' D' R' B L2 D)\n"
		"(L' D' L' B R' D)\n"
		"(L' D' B R' L2 D)\n"
		"(F U L U R2 D)\n"
		"(F U L' U R2 D)\n"
		"(F U2 L U' R2 D)\n"
		"(F U2 L' U' R2 D)\n"
		"(F' R U R2 L' D)\n"
		"(F' B R U' L2 D)\n"
		"(F' B R' U' L2 D)\n"
		"(B2 R U L2 B D)\n"
		"(B2 R' U L2 B D)\n"
		"(F' B2 D R D U)\n"
		"(F' B2 D R' D U)\n"
		"(B2 D F' R D U)\n"
		"(B2 D F' R' D U)\n"
		"U (R' D U2 L' U)\n"
		"U (R' D F R U)\n"
		"U (R' D' U2 L' U)\n"
		"U (R' D' F R U)\n"
		"U (R' F2 D R U)\n"
		"U (R' F2 D' R U)\n"
		"U (R U F' R' D)\n"
		"U (R U' F' R' D)\n"
		"U (R D2 U L D)\n"
		"U (R D2 U' L D)\n"
		"U (R F2 U R' D)\n"
		"U (R F2 U' R' D)\n"
		"U (R2 F2 R D U)\n"
		"U (R2 F2 R' D U)\n"
		"U (L2 B2 R D U)\n"
		"U (L2 B2 R' D U)\n"
		"U R' U (R' L2 D)\n"
		"U2 R' B' U (R' D)\n"
		"U' L U (R' L D)\n"
		"U' L B U (R' D)\n"
		"R L F2 U (L D)\n"
		"R F2 L U (L D)\n"
		"R F' U (F2 R U)\n"
		"R2 F' U (R F2 U)\n"
		"R2 F' U (F' R U)\n"
		"R' L F' U (R' D)\n"
		"R' L2 U (R B2 U)\n"
		"R' L2 U (B2 R U)\n"
		"R' F' L U (R' D)\n"
		"L U2 B U (R' D)\n"
		"L F' U (D2 L D)\n"
		"L F' U (F' R' D)\n"
		"L F' R U (L D)\n"
		"L2 F U (R' F' D)\n"
		"F U (F' U R' D)\n"
		"F U (F' U' R' D)\n"
		"F D' R2 U (F U)\n"
		"F2 U (D R F U)\n"
		"F2 U (D' R F U)\n"
		"F2 U (F' D R U)\n"
		"F2 U (F' D' R U)\n"
		"F2 R' L' U (L2 D)\n"
		"F' U (D' F2 R U)\n"
		"F' D' R2 U (F U)\n"
		"F' R L U (L D)\n"
		"F' R2 U (F2 R U)\n"
		"F' L U (D2 L D)\n"
		"F' L U (F' R' D)\n"
		"B U (B2 R D U)\n"
		"B U (B2 R' D U)\n"
		"U F2 B' D (R U)\n"
		"R U F D (R' U)\n"
		"R U' F D (R' U)\n"
		"R B D (L' F D)\n"
		"R B D (F L' D)\n"
		"R B2 D (L2 F D)\n"
		"R B2 D (F L2 D)\n"
		"R' U F' B' D (U)\n"
		"R' U B' D (R2 U)\n"
		"R' U' F' B' D (U)\n"
		"R' U' B' D (R2 U)\n"
		"R' L' B2 D (L D)\n"
		"R' B D (F' L' D)\n"
		"R' B L' D (L D)\n"
		"R' B2 D (L F' D)\n"
		"R' B2 D (F' L2 D)\n"
		"L' B2 R' D (L D)\n"
		"L' B' R' D (L' D)\n"
		"F D (R' F B' U)\n"
		"F D (F R' B' U)\n"
		"F U' B2 D (F U)\n"
		"F R' U B' D (U)\n"
		"F R' U' B' D (U)\n"
		"F B2 D (U' F U)\n"
		"F B' D (U B' U)\n"
		"F2 B' D (R B' U)\n"
		"F2 B' D (B' R U)\n"
		"F' U' B2 D (F U)\n"
		"F' B' D (F' B' U)\n"
		"B D (B L F D)\n"
		"B R' D (F' L' D)\n"
		"B R' L' D (L D)\n"
		"B2 D (R2 F B U)\n"
		"B2 D (L2 F B D)\n"
		"B2 R D (L F D)\n"
		"B2 R' D (L F' D)\n"
		"B2 R' D (F' L2 D)\n"
		"B2 R' L' D (L2 D)\n"
		"B' D (R F' B' U)\n"
		"B' D (F' R2 B' U)\n"
		"B' D (F' B' R2 U)\n"
		"B' D (B' R F' U)\n"
		"B' D (L' F B D)\n"
		"B' D (F L' B D)\n"
		"B' D (F B L2 D)\n"
		"B' D (B L2 F D)\n"
		"B' R D (L2 F D)\n"
		"B' R D (F L2 D)\n"
		"B' R' D (L2 F' D)\n"
},
[18] = {
	.scramble = "D2 R D B2 U2 B R F U2 L' D2 R2 D2 R2 D' F2 L2 F2 U R2 D'",
	.solutions =
		"U (D R D)\n"
		"B U (R D)\n"
},
[19] = {
	.scramble = "B' D' F B' U' R U' R' D' F' D2 B2 R' L2 D2 L' B2 L' B2 L2 U2 F2",
	.solutions =
		"U (R2 F U)\n"
		"U (F R2 U)\n"
		"F U (R2 U)\n"
},
{
	.scramble = "", /* End-of-list signal */
}
};
